### ISSUE TITLE
hook up travis ci to deploy to pypi from git tags

### ISSUE THREAD

**Issue by mrtazz** [mrtazz/simplenote.py#10]
mo automation, less hassle

**Comment by atomicules** [comment]
Deploying is still broken, and I think it is still because of Travis: https://github.com/travis-ci/travis-ci/issues/1675

**Comment by atomicules** [comment]
All working now. See #14.

**Comment by mrtazz** [comment]
Ugh I totally forgot about this open issue. Thanks for fixing it @atomicules!

**Comment by atomicules** [comment]
For reference see this comment about limiting build concurrency:

https://github.com/mrtazz/simplenote.py/pull/13#issuecomment-77597012

The Travis blog post is here:

http://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/

This setting has been applied on Travis for this repository.
