### ISSUE TITLE
Update to the new Simperium API

### ISSUE THREAD

**Issue by atomicules** [mrtazz/simplenote.py#11]
Since it has been out for awhile. I don't know what the plans are for the old one, but I guess it won't be kept forever.

**Comment by atomicules** [comment]
On hold because Simplenote seem to be in no rush to roll out this API so there is no way to properly use it yet.

**Comment by noamelf** [comment]
@atomicules the "old" API seems to stop working. On `get_token` I receive a 400 code... Are you familiar with that?

**Comment by atomicules** [comment]
Hi. Still working for me here. Worrying that they'd turn off the old 
API without finishing off the new one.

**Comment by atomicules** [comment]
I've still got access to the old API docs and a 400 error is a bad 
request (It suggests to check parameters).

Have you double-checked your logon details?

**Comment by noamelf** [comment]
@atomicules I'm using `simplenote==1.0.3`, with the same credentials I login in their web UI.

The code that fails is like so:
```python
simplenote = simplenote.Simplenote(email, pswd)
simplenote.get_token()
```

**Comment by atomicules** [comment]
Weird. Definitely not seeing issues here. Is this a new Simplenote 
account? Wondering if it's something to do with that?

Can you run the tests ok? That uses a generic account.

**Comment by noamelf** [comment]
The tests passes :)

**Comment by Viqsi** [comment]
I think this just shot up in importance. The generic account in the tests no longer seems to work (nor does my actual user account, for the record).

**Comment by atomicules** [comment]
Well that sucks, especially because they never opened the new API.

Just noticed they updated this page: https://simplenote.com/developers/

> Some older applications may still be using the legacy Simplenote API at https://simple-note.appspot.com. Note that this API has been deprecated and will no longer function after October 1, 2018.

A bit early with the shut off.

> We give access to the Simperium API for Simplenote on a case-by-case basis.

My last email exchange with the Simplenote folk was 2014. When they said:

> So on our end, we plan to allow users to grab a 3rd party API token from the Simplenote website (settings page). They could then use this with 3rd party apps that interact
directly with Simperium (the API token would be a Simperium auth token).

They never did that so the only way to use the Simperium API at the moment is:

> To get your own token for dev right now, load the Simplenote web app: https://app.simplenote.com
Open the javascript console, and grab it from: "simperium_opts['token']"

Which is going to be annoying for everyone to do.

I'll email them again and see what the plans are.

**Comment by atomicules** [comment]
Seems the Simperium API now does do authorisation... so will look at switching this over.

**Comment by atomicules** [comment]
Hmm... we still need an API key though.

**Comment by atomicules** [comment]
Will wait to hear what they say by email.

**Comment by atomicules** [comment]
simperium tokens seem fairly persistent... so one way is just have people go grab it from the web api (via the web browser developer console). And we just use that for auth.

**Comment by Viqsi** [comment]
Well, now, this is interesting. Muscle memory induced an unintended retest of use of the old API, and thus did I discover it's working again. I guess someone there noticed after a week that it'd been accidentally shut down early or something.

Hopefully that means we've gone from "oh crap it's already gone" to "we've got about six weeks to make this happen".

**Comment by atomicules** [comment]
Work being tracked here: #22

**Comment by atomicules** [comment]
Done.
