### ISSUE TITLE
update_note() modifies the note object passed by argument

### ISSUE THREAD

**Issue by yuuki0xff** [mrtazz/simplenote.py#26]
The update_note() modifies the note object passed by argument.  The behavior is not documented and unexpected for users.  Can you please fix it?

```
$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import simplenote
>>> sn = simplenote.Simplenote('user', 'password')
>>> note = {'modifydate': 2.0, 'createdate': 1.0, 'tags': [], 'content': 'note'}
>>> sn.update_note(note)
({u'modifydate': 2.0, u'tags': [], u'deleted': False, u'createdate': 1.0, u'shareURL': u'', u'publishURL': u'', u'systemtags': [], u'content': u'note', u'version': 1, u'systemTags': [], u'key': 'd8d0d7d0d4524bf49e504fd42f3e5c74', u'modificationDate': 2.0, u'creationDate': 1.0}, 0)
>>> note
{'tags': [], 'deleted': False, 'shareURL': '', 'systemTags': [], 'content': 'note', 'publishURL': '', 'modificationDate': 2.0, 'creationDate': 1.0}
>>>
```

Related: cpbotha/nvpy#181

**Comment by atomicules** [comment]
Woah... leaky. Interesting. Sure I shall take a look. Guessing that comes from adding all the required fields (`__add_simplenote_api_fields`) and I've done something a bit wrong there.

**Comment by atomicules** [comment]
Will get to this soon... hopefully. Just snowed under with stuff at the mo'.

**Comment by atomicules** [comment]
Probably just as simple as that commit ^ will try to have a quick scan through and see if anything else needs fixing similarly though before merging in.

**Comment by atomicules** [comment]
Sorry that took so long.

**Comment by yuuki0xff** [comment]
Thanks!
